version: "3"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - .mysql:/var/lib/mysql
    ports:
      - "${DATABASE_PORT}:3306"
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - backend
  backend:
    image: repository-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - "${BACKEND_PORT}:4000"
    networks:
      - backend
    depends_on:
      - mysql
    volumes:
      - ./backend:/usr/src/app
networks:
  backend:
    driver: bridge
